/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SyncCheckRouteImport } from './routes/sync-check'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as GithubGuideRouteImport } from './routes/github-guide'
import { Route as EnRouteImport } from './routes/en'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GoTargetRouteImport } from './routes/go.$target'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SyncCheckRoute = SyncCheckRouteImport.update({
  id: '/sync-check',
  path: '/sync-check',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const GithubGuideRoute = GithubGuideRouteImport.update({
  id: '/github-guide',
  path: '/github-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const EnRoute = EnRouteImport.update({
  id: '/en',
  path: '/en',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GoTargetRoute = GoTargetRouteImport.update({
  id: '/go/$target',
  path: '/go/$target',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/en': typeof EnRoute
  '/github-guide': typeof GithubGuideRoute
  '/privacy': typeof PrivacyRoute
  '/sync-check': typeof SyncCheckRoute
  '/terms': typeof TermsRoute
  '/go/$target': typeof GoTargetRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/en': typeof EnRoute
  '/github-guide': typeof GithubGuideRoute
  '/privacy': typeof PrivacyRoute
  '/sync-check': typeof SyncCheckRoute
  '/terms': typeof TermsRoute
  '/go/$target': typeof GoTargetRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/en': typeof EnRoute
  '/github-guide': typeof GithubGuideRoute
  '/privacy': typeof PrivacyRoute
  '/sync-check': typeof SyncCheckRoute
  '/terms': typeof TermsRoute
  '/go/$target': typeof GoTargetRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accessibility'
    | '/en'
    | '/github-guide'
    | '/privacy'
    | '/sync-check'
    | '/terms'
    | '/go/$target'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accessibility'
    | '/en'
    | '/github-guide'
    | '/privacy'
    | '/sync-check'
    | '/terms'
    | '/go/$target'
  id:
    | '__root__'
    | '/'
    | '/accessibility'
    | '/en'
    | '/github-guide'
    | '/privacy'
    | '/sync-check'
    | '/terms'
    | '/go/$target'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessibilityRoute: typeof AccessibilityRoute
  EnRoute: typeof EnRoute
  GithubGuideRoute: typeof GithubGuideRoute
  PrivacyRoute: typeof PrivacyRoute
  SyncCheckRoute: typeof SyncCheckRoute
  TermsRoute: typeof TermsRoute
  GoTargetRoute: typeof GoTargetRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sync-check': {
      id: '/sync-check'
      path: '/sync-check'
      fullPath: '/sync-check'
      preLoaderRoute: typeof SyncCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/github-guide': {
      id: '/github-guide'
      path: '/github-guide'
      fullPath: '/github-guide'
      preLoaderRoute: typeof GithubGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en': {
      id: '/en'
      path: '/en'
      fullPath: '/en'
      preLoaderRoute: typeof EnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/go/$target': {
      id: '/go/$target'
      path: '/go/$target'
      fullPath: '/go/$target'
      preLoaderRoute: typeof GoTargetRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessibilityRoute: AccessibilityRoute,
  EnRoute: EnRoute,
  GithubGuideRoute: GithubGuideRoute,
  PrivacyRoute: PrivacyRoute,
  SyncCheckRoute: SyncCheckRoute,
  TermsRoute: TermsRoute,
  GoTargetRoute: GoTargetRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
